[package]
name = "sherlock-ip-sniffer"
version = "0.1.0"
authors = ["CynicNyctophile"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bpaf = {version = "0.7", features = ["derive", "bright-color"]}